### ISSUE TITLE
编译不过

### ISSUE THREAD

**Issue by zorrohahaha** [alibaba/tair#14]
src/storage/ldb/leveldb/ax_port_leveldb.m4:15: the top level
configure.ac:113: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2590: _AC_COMPILE_IFELSE is expanded from...
../../lib/autoconf/general.m4:2606: AC_COMPILE_IFELSE is expanded from...
../../lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
../../lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
../../lib/autoconf/general.m4:2052: AC_CACHE_CHECK is expanded from...
ax_boost.m4:43: AX_BOOST is expanded from...
configure.ac:113: the top level
configure.ac:3: warning: AM_INIT_AUTOMAKE: two- and three-arguments forms are deprecated.  For more info, see:
configure.ac:3: http://www.gnu.org/software/automake/manual/automake.html#Modernize-AM_005fINIT_005fAUTOMAKE-invocation
configure.ac:123: error: required file 'test/Makefile.in' not found
configure.ac:123: error: required file 'test/interface_test/Makefile.in' not found
configure.ac:123: error: required file 'test/unit_test/Makefile.in' not found
configure.ac:123: error: required file 'test/statistics_test/Makefile.in' not found
configure.ac:123: error: required file 'test/retry_all_test/Makefile.in' not found
Makefile.am:2: error: required directory ./test does not exist
Makefile.am:5: error: required directory ./test does not exist

**Comment by hailiu16** [comment]
configure.ac:
AC_CONFIG_FILES([\
		 Makefile \
		 src/Makefile \
		 src/common/Makefile \
		 src/plugin/Makefile \
		 src/storage/Makefile \
		 src/storage/fdb/Makefile \
		 src/storage/mdb/Makefile \
		 src/storage/kdb/Makefile \
		 src/storage/kdb/kyotocabinet/Makefile \
		 src/storage/ldb/Makefile \
		 src/storage/ldb/leveldb/Makefile \
		 src/packets/Makefile \
		 src/statserver/storage/Makefile \
		 src/statserver/Makefile \
		 src/statserver/include/Makefile \
		 src/configserver/Makefile \
		 src/dataserver/Makefile \
		 src/client/Makefile \
		 src/invalserver/Makefile \
		 src/tools/Makefile \
		 test/Makefile \
		 test/interface_test/Makefile \
		 test/unit_test/Makefile \
		 test/statistics_test/Makefile \
		 test/retry_all_test/Makefile \
		 scripts/Makefile \
		 share/Makefile
		 ])


中的test应该是用来测试的  是不是可以注释掉

**Comment by hurley25** [comment]
新版本已经发布，可以测试编译了。
