### ISSUE TITLE
哪里找文档呢？

### ISSUE THREAD

**Issue by Andy-Amoy** [alibaba/tair#19]
上一个issue被关闭说是会逐步更新文档到这里。但是至今wiki只有简单的介绍，而且淘宝code上的页面早就无法打开，返回403 forbidden了。wiki的更新有时间表吗？

**Comment by hurley25** [comment]
文档会逐步更新上去，基本的配置使用会在3月份更新完毕。

**Comment by XiaoguangMo** [comment]
支持一下

**Comment by rl5c** [comment]
一直用v2.3，用到天荒地老，终于有动静了。
storage driver 有没有支持redis的方案呢？
