### ISSUE TITLE
编译不成功

### ISSUE THREAD

**Issue by Landy0104** [alibaba/tair#20]
经查看，是libeasy编译有问题，没有生成libeasy库。

**Comment by hurley25** [comment]
https://github.com/alibaba/tair/wiki/Tair-%E7%BC%96%E8%AF%91%E5%AE%89%E8%A3%85%E6%96%B9%E6%B3%95

**Comment by Landy0104** [comment]
非常谢谢，编译成功，测试成功！非常感谢

**Comment by Landy0104** [comment]
之前在ubuntun上编译，没有成功，今天上午换成centos6.5上面，编译测试成功！

**Comment by hurley25** [comment]
不客气，我们只在CentOS6/7上测试过
