### ISSUE TITLE
关于tair3.2.4

### ISSUE THREAD

**Issue by rl5c** [alibaba/tair#22]
hi team!
我们现在正在使用tair2.3.x版本，并且部署到了产线，想问问若升级到tair3.2.4版本，底层协议与是否是兼容老版本，我试了试tair2.3.x的tairclient连接到tair3.2.4的configserver，目前是没问题的，有没有需要注意的地方？这方面我看文档没有这么阐述。另外这两个版本的差别有多大？
感谢，望回复。

**Comment by hurley25** [comment]
客户端协议是兼容的。

**Comment by rl5c** [comment]
请问文档还会补充完整吗？关于rdb存储引擎有没有后续的安排？
