### ISSUE TITLE
libeasy文档中地址不可访问

### ISSUE THREAD

**Issue by wadeliuyi** [alibaba/tair#26]
1. 数据包的处理过程
        见图 http://baike.corp.taobao.com/index.php/File:Easy%E6%95%B0%E6%8D%AE%E6%B5%81%E7%A8%8B%E5%9B%BE.png

**Comment by hurley25** [comment]
![image](https://user-images.githubusercontent.com/1798641/53469564-60cd8600-3a99-11e9-9deb-7011b1858b55.png)

**Comment by QGB** [comment]
···
 
http://baike.corp.taobao.com/index.php
 
技术信息： 错误 connectionfailure
···

淘宝关了这个站点吗
