### ISSUE TITLE
wiki文档内容没有协议部分，应该在哪里提问？

### ISSUE THREAD

**Issue by chubbyerror** [alibaba/tair#28]
看了一下客户端的代码是用httpclient实现的，但是提交部分的编码方式没有文档，Wiki也只有一些基础的使用问题，并没有深入的这部分的文档，如果有这部分的文档需求应该取哪里查看呢？

**Comment by hurley25** [comment]
暂时没有公开的文档，src/packets 下有具体的实现，packets/packet.hpp 包含了除了魔数之外的协议头，具体的协议比如 get 可以看  src/packets/get_packet.hpp 的 decode、encode，服务端解码过程在 src/packets/packet_factory.cpp#L76

**Comment by chubbyerror** [comment]
> 暂时没有公开的文档，src/packets 下有具体的实现，packets/packet.hpp 包含了除了魔术之外的协议头，具体的协议比如 get 可以看 src/packets/get_packet.hpp 的 decode、encode，服务端解码过程在 src/packets/packet_factory.cpp#L76

java客户端那边issue也可以提在这边，那边也做了完整的实现，他们那边会不会有完整的协议文档或参考文档？

**Comment by hurley25** [comment]
两边是一样的，暂时都没有能对外提供的协议文档。
