### ISSUE TITLE
后续更新吗？ 希望增加点文档

### ISSUE THREAD

**Issue by melin** [alibaba/tair#30]
后续更新吗？ 希望增加点文档。

**Comment by hurley25** [comment]
系统趋于稳定状态，代码上的更新不会太多，主要是不定期的 bugfix
文档指的是哪方面的呢？使用还是设计？

**Comment by melin** [comment]
最好是有使用文档，怎么编译、部署、客户端怎么使用，缺少java client，如果能够完善这块文档，还是有不少的用户。tair 能够解决不少用户需求。
我们现在存储kv数据，使用的产品比较多：Cassandra Aerospike hbase redis，维护成本比较大。。。。

**Comment by hurley25** [comment]
编译、部署现在 wiki 里有，Java 客户端暂时只有个早期的
https://github.com/alibaba/tair-java-client

**Comment by melin** [comment]
> 编译、部署现在 wiki 里有，Java 客户端暂时只有个早期的
> https://github.com/alibaba/tair-java-client
谢谢，tair-java-client 可以更新？

**Comment by hurley25** [comment]
tair-java-client 暂时没有计划，相关的内部依赖太多，很难剥离

**Comment by jasonjoo2010** [comment]
java client我们内部有个修正＋增强版的，适配tair-2.3（非libeasy版），不知道跟3.2版本api是否一致
