### ISSUE TITLE
tair 有支持批量导入吗？

### ISSUE THREAD

**Issue by melin** [alibaba/tair#31]
tair 有支持批量导入吗？ 指标数据，一般都非常大，一般离线算好，提供线上使用，一般都是几亿条，insert 操作太慢，现在只能选择hbase ，生成hfile，批量导入。

**Comment by hurley25** [comment]
内部系统有，但是上下游牵扯太多内部系统，暂无开源计划。

**Comment by jasonjoo2010** [comment]
看量级，和业务特点

如果是系统初建时导入，那就多线程直接插就可以了，效率应该能达到数万qps
如果是一个长期批量的行为，那建议还是建立任务，在流控下导入

如果是有prefix的数据，那么同prefix下合并，小块小块地插入效率是最快的
