### ISSUE TITLE
RANGE_ALL_REVERSE  in get_range is not implemented

### ISSUE THREAD

**Issue by jasonjoo2010** [alibaba/tair#34]
as the title

So can code get updated?

Or we can only reimplement it

**Comment by hurley25** [comment]
RANGE_ALL_REVERSE not support yet

**Comment by jasonjoo2010** [comment]
> RANGE_ALL_REVERSE not support yet

Yep.
We just begin to implement it including enlarging the cdate/mdate/edate to int64_t and so on. And the same to `tair3-client`. After all it's not compatible with tair2 so I think it's okey to have a fresh beginning.

**Comment by jasonjoo2010** [comment]
So `OTS` is not tair, right? They are similar though but have some difference.

**Comment by hurley25** [comment]
Yes，OTS is not tair

**Comment by jasonjoo2010** [comment]
> Yes，OTS is not tair

Thanks.


And `tair_proxy` and `rpc` support haven't been opened source? Though they are not that difficult to write a protocol proxy using libeasy.

**Comment by jasonjoo2010** [comment]
Oh I implemented an alternative version for both tair3[1] and tair3-client[2].

The main features:
* get_range support reversed traversal.
* enlarge expire to int64.
* enlarge counter to int64.

Later I will merge the related codes from old version(2.x) supporting slave reading, 4 or 5 copies, local preferred reading in environment of multiple(or double) IDC.

If you have any interest or any further thought please let me know. It's a pity the life cycle of tair is dying(likely because even there wan't a java client officially).

[1] https://github.com/jasonjoo2010/tair/tree/3.3.x#330
[2] https://github.com/yoloho/tair3-client/tree/3.3.0
