### ISSUE TITLE
tair-java-client 代码是不是也迁移过来，现在taocode的trunk编译有错误

### ISSUE THREAD

**Issue by ahypnos** [alibaba/tair#6]
现在TaoCode上的 http://code.taobao.org/svn/tair-client-java/trunk 签出的代码编译有错误，能不能也迁移到github上，并解决一下编译问题。

**Comment by amwicfai** [comment]
同问

**Comment by c9n** [comment]
代码还更新么？

**Comment by dutor** [comment]
@ahypnos @amwicfai @c9n 一个外部版本的 Tair 刚刚开始开发（基于阿里内部使用的版本，但重新实现无法开源的依赖）。届时 Java 客户端也为一并给出，欢迎关注。https://github.com/lotair/tair
